### ISSUE TITLE
OSError：Unable to open object (bad object header version number)

### ISSUE THREAD

**Issue by wenli4313** [fabiopoiesi/dip#10]
Hi!
When I run "train.py" using the preprocessed data， I got the error"OSError：Unable to open object (bad object header version number)". I don't know how to solve.Do you have any ideas please?Thank you very much.

**Comment by fabiopoiesi** [comment]
Which is the command that gives this error?

**Comment by wenli4313** [comment]
There may be an error when loading data.

Traceback (most recent call last):
  File "/home/dell/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-78f7f7391e47>", line 1, in <module>
    runfile('/home/dell/dip-master/train.py', wdir='/home/dell/dip-master')
  File "/home/dell/pycharm-community-2020.3.5/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/dell/pycharm-community-2020.3.5/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/dell/dip-master/train.py", line 42, in <module>
    dataset = Dataset(dataset_root, dataset_name, dataset_to_train, ratio_to_eval, do_data_augmentation)
  File "/home/dell/dip-master/dataset.py", line 40, in __init__
    hf = h5py.File(os.path.join(self.root_ptcld_overlap, f), 'r')
  File "/home/dell/anaconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 458, in __init__
    swmr=swmr)
  File "/home/dell/anaconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 199, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 100, in h5py.h5f.open
OSError: Unable to open file (bad object header version number)

**Comment by fabiopoiesi** [comment]
Did you solve this issue?

**Comment by wenli4313** [comment]
Thank&nbsp; you！ This problem was solved。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月23日(星期二) 凌晨4:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fabiopoiesi/dip] OSError：Unable to open object (bad object header version number) (#10)





 
Did you solve this issue?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xiaochuangshu** [comment]
how do you solve this issue,could you tell me ,thank you  very much,if you see this message,you can connect with me wechat:Chaseforproactive
